# Practical_6: Numpy

In [1]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [13]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [19]:
y = np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [33]:
z = np.linspace(0,5,10, endpoint = False)
z

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [35]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [43]:
b = np.random.random((4,4))
b

array([[0.97287352, 0.18475826, 0.84337712, 0.36771583],
       [0.35741937, 0.61534169, 0.9173619 , 0.04720599],
       [0.16536584, 0.20948086, 0.63668953, 0.21595701],
       [0.74977675, 0.69667224, 0.6372795 , 0.25629931]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [45]:
np.shape(b)

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [56]:
c1 = np.arange(16)
np.reshape(c1,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
     

In [58]:
c2 = np.arange(16).reshape((4,4))
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [70]:
c2.dtype

dtype('int32')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [78]:
d = np.arange(1, 101)
d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [93]:
even_d = (d%2==0) #create  a mask
d[even_d] #obtain values of d that are true in the mask

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [124]:
e = np.random.randint(10, 50, (6,6))
e

array([[45, 26, 14, 10, 19, 36],
       [18, 34, 30, 21, 26, 35],
       [30, 42, 38, 25, 24, 27],
       [25, 49, 48, 37, 26, 18],
       [20, 46, 28, 43, 35, 40],
       [23, 45, 30, 46, 49, 30]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [116]:
e[2:4,]

array([[25, 33, 25, 12, 12, 19],
       [39, 31, 26, 39, 40, 16]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [108]:
np.sum(e)

1072

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [130]:
e

array([[45, 26, 14, 10, 19, 36],
       [18, 34, 30, 21, 26, 35],
       [30, 42, 38, 25, 24, 27],
       [25, 49, 48, 37, 26, 18],
       [20, 46, 28, 43, 35, 40],
       [23, 45, 30, 46, 49, 30]])

In [136]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
print(np.mean(e))
print(np.mean(c))

31.61111111111111
7.5


In [140]:
print(np.median(e))
print(np.median(c))

30.0
7.5


In [142]:
print(np.std(e))
print(np.std(c))

10.52055601027969
4.6097722286464435


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [150]:
e

array([[45, 26, 14, 10, 19, 36],
       [18, 34, 30, 21, 26, 35],
       [30, 42, 38, 25, 24, 27],
       [25, 49, 48, 37, 26, 18],
       [20, 46, 28, 43, 35, 40],
       [23, 45, 30, 46, 49, 30]])

In [156]:
print(np.max(e))
print(np.min(e))

49
10


In [146]:
help(np.max)

Help on _ArrayFunctionDispatcher in module numpy:

max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the maximum of an array or maximum along an axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.

    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will 

In [164]:
print(np.max(e, axis=0)) #gives the maximum of each column, i.e axis 0
print(np.min(e, axis=0)) #gives the minimum of each column, i.e axis 0

[45 49 48 46 49 40]
[18 26 14 10 19 18]


In [166]:
print(np.max(e, axis=1)) #gives the maximum of each row, i.e axis 1
print(np.min(e, axis=1)) # gives the minimum of each row, i.e axis 1

[45 35 42 49 46 49]
[10 18 24 18 20 23]


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [182]:
f = np.random.randint(20, size = (1,20))
print(f)
print(np.max(f))

[[ 2  2  1  9  0  9 19 19 18 10  6 18  0 13  1  2 19 13  1  1]]
19


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [418]:
f

array([[ 2,  2,  1,  9,  0,  9, 19, 19, 18, 10,  6, 18,  0, 13,  1,  2,
        19, 13,  1,  1]])

In [416]:
np.flip(f)

array([[ 1,  1, 13, 19,  2,  1, 13,  0, 18,  6, 10, 18, 19, 19,  9,  0,
         9,  1,  2,  2]])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [214]:
g = np.random.randint(1, 9,(3,3))
g

array([[7, 3, 7],
       [8, 5, 2],
       [8, 1, 3]])

In [216]:
h = np.arange(9).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [230]:
g*h

array([[ 0,  3, 14],
       [24, 20, 10],
       [48,  7, 24]])

In [224]:
help(np.product)

Help on _ArrayFunctionDispatcher in module numpy:

product(*args, **kwargs)
    Return the product of array elements over a given axis.

    .. deprecated:: 1.25.0
        ``product`` is deprecated as of NumPy 1.25.0, and will be
        removed in NumPy 2.0. Please use `prod` instead.

    See Also
    --------
    prod : equivalent function; see for details.



### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [228]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [226]:
np.diag(x)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [239]:
i = np.random.randint(1,20, (4,4))
j = np.random.randint(1,8,(4,2))
print(i)
print(j)

[[19  3  2  7]
 [ 7 13 15 12]
 [ 3 12  1 18]
 [ 6  9  4 12]]
[[7 6]
 [6 1]
 [3 6]
 [2 1]]


In [243]:
np.dot(i, j)

array([[171, 136],
       [196, 157],
       [132,  54],
       [132,  81]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [262]:
np.ndarray.flatten(i) #default order is C

array([19,  3,  2,  7,  7, 13, 15, 12,  3, 12,  1, 18,  6,  9,  4, 12])

In [266]:
np.ndarray.flatten(i, order = 'F')

array([19,  7,  3,  6,  3, 13, 12,  9,  2, 15,  1,  4,  7, 12, 18, 12])

In [268]:
np.ndarray.flatten(i, order = 'A')

array([19,  3,  2,  7,  7, 13, 15, 12,  3, 12,  1, 18,  6,  9,  4, 12])

In [270]:
np.ndarray.flatten(i, order = 'K')

array([19,  3,  2,  7,  7, 13, 15, 12,  3, 12,  1, 18,  6,  9,  4, 12])

In [272]:
np.ndarray.flatten(i, order = 'C')

array([19,  3,  2,  7,  7, 13, 15, 12,  3, 12,  1, 18,  6,  9,  4, 12])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [290]:
np.stack((b,c2), axis = 0) #stack by row by specifying axis = 0

array([[[ 0.97287352,  0.18475826,  0.84337712,  0.36771583],
        [ 0.35741937,  0.61534169,  0.9173619 ,  0.04720599],
        [ 0.16536584,  0.20948086,  0.63668953,  0.21595701],
        [ 0.74977675,  0.69667224,  0.6372795 ,  0.25629931]],

       [[ 0.        ,  1.        ,  2.        ,  3.        ],
        [ 4.        ,  5.        ,  6.        ,  7.        ],
        [ 8.        ,  9.        , 10.        , 11.        ],
        [12.        , 13.        , 14.        , 15.        ]]])

In [292]:
np.stack((b,c2), axis = -1) #stack by columns by specifying axis = -1

array([[[ 0.97287352,  0.        ],
        [ 0.18475826,  1.        ],
        [ 0.84337712,  2.        ],
        [ 0.36771583,  3.        ]],

       [[ 0.35741937,  4.        ],
        [ 0.61534169,  5.        ],
        [ 0.9173619 ,  6.        ],
        [ 0.04720599,  7.        ]],

       [[ 0.16536584,  8.        ],
        [ 0.20948086,  9.        ],
        [ 0.63668953, 10.        ],
        [ 0.21595701, 11.        ]],

       [[ 0.74977675, 12.        ],
        [ 0.69667224, 13.        ],
        [ 0.6372795 , 14.        ],
        [ 0.25629931, 15.        ]]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [294]:
np.stack((b,c2), axis = -1) #stack by columns by specifying axis = -1

array([[[ 0.97287352,  0.        ],
        [ 0.18475826,  1.        ],
        [ 0.84337712,  2.        ],
        [ 0.36771583,  3.        ]],

       [[ 0.35741937,  4.        ],
        [ 0.61534169,  5.        ],
        [ 0.9173619 ,  6.        ],
        [ 0.04720599,  7.        ]],

       [[ 0.16536584,  8.        ],
        [ 0.20948086,  9.        ],
        [ 0.63668953, 10.        ],
        [ 0.21595701, 11.        ]],

       [[ 0.74977675, 12.        ],
        [ 0.69667224, 13.        ],
        [ 0.6372795 , 14.        ],
        [ 0.25629931, 15.        ]]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [298]:
np.split(i,4) #split function splits an array into sub-arrays. The arguments here are(matrix, no. of sub-arrays to split array into)

[array([[19,  3,  2,  7]]),
 array([[ 7, 13, 15, 12]]),
 array([[ 3, 12,  1, 18]]),
 array([[ 6,  9,  4, 12]])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [306]:
b

array([[0.97287352, 0.18475826, 0.84337712, 0.36771583],
       [0.35741937, 0.61534169, 0.9173619 , 0.04720599],
       [0.16536584, 0.20948086, 0.63668953, 0.21595701],
       [0.74977675, 0.69667224, 0.6372795 , 0.25629931]])

In [304]:
np.round(b, decimals = 2)

array([[0.97, 0.18, 0.84, 0.37],
       [0.36, 0.62, 0.92, 0.05],
       [0.17, 0.21, 0.64, 0.22],
       [0.75, 0.7 , 0.64, 0.26]])

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [310]:
g

array([[7, 3, 7],
       [8, 5, 2],
       [8, 1, 3]])

In [308]:
np.unique(g)

array([1, 2, 3, 5, 7, 8])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [312]:
i

array([[19,  3,  2,  7],
       [ 7, 13, 15, 12],
       [ 3, 12,  1, 18],
       [ 6,  9,  4, 12]])

In [322]:
mask = (i < 7) #identifies values in matrix satisfyingthe condition and denotes them True
i[mask] = 7 #for all entries that are true replace with 7
i

array([[19,  7,  7,  7],
       [ 7, 13, 15, 12],
       [ 7, 12,  7, 18],
       [ 7,  9,  7, 12]])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [326]:
i

array([[19,  7,  7,  7],
       [ 7, 13, 15, 12],
       [ 7, 12,  7, 18],
       [ 7,  9,  7, 12]])

In [324]:
np.cumsum(i)

array([ 19,  26,  33,  40,  47,  60,  75,  87,  94, 106, 113, 131, 138,
       147, 154, 166])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [330]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [336]:
k = np.nonzero(a) #gives index of these non-zero values
a[k]

array([1., 1., 1., 1., 1.])

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [347]:
l = np.random.randint(30,70, (4,7))
l

array([[67, 63, 46, 35, 42, 40, 63],
       [33, 35, 59, 47, 56, 32, 67],
       [31, 35, 34, 34, 60, 46, 66],
       [65, 55, 38, 37, 61, 30, 63]])

In [351]:
np.sort(l) #values of the matrix are sorted from smallest to largest

array([[35, 40, 42, 46, 63, 63, 67],
       [32, 33, 35, 47, 56, 59, 67],
       [31, 34, 34, 35, 46, 60, 66],
       [30, 37, 38, 55, 61, 63, 65]])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [360]:
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [366]:
np.sum(h, axis = 0) #column-wise sum

array([ 9, 12, 15])

In [368]:
np.sum(h, axis = 1) #row-wise sum

array([ 3, 12, 21])

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [372]:
m = np.random.randint(20,50,(7,7))
m

array([[30, 33, 28, 40, 44, 36, 34],
       [29, 27, 31, 46, 34, 43, 38],
       [28, 31, 44, 23, 37, 37, 46],
       [35, 31, 38, 44, 37, 42, 43],
       [31, 26, 24, 33, 45, 21, 46],
       [25, 24, 42, 25, 20, 49, 26],
       [49, 43, 30, 29, 47, 22, 22]])

In [394]:
n = np.linalg.norm(m) #returns norm
o = m/n #divide matrix values by norms to obtain values between 0 and 1
o

array([[0.12088522, 0.13297374, 0.11282621, 0.16118029, 0.17729832,
        0.14506226, 0.13700325],
       [0.11685571, 0.1087967 , 0.12491473, 0.18535734, 0.13700325,
        0.17326881, 0.15312128],
       [0.11282621, 0.12491473, 0.17729832, 0.09267867, 0.14909177,
        0.14909177, 0.18535734],
       [0.14103276, 0.12491473, 0.15312128, 0.17729832, 0.14909177,
        0.16923931, 0.17326881],
       [0.12491473, 0.10476719, 0.09670818, 0.13297374, 0.18132783,
        0.08461965, 0.18535734],
       [0.10073768, 0.09670818, 0.16923931, 0.10073768, 0.08059015,
        0.19744586, 0.10476719],
       [0.19744586, 0.17326881, 0.12088522, 0.11685571, 0.18938684,
        0.08864916, 0.08864916]])

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [400]:
p = np.random.random(25).reshape((5,5))
p

array([[0.75719501, 0.38083885, 0.73811989, 0.67170711, 0.53542229],
       [0.77389499, 0.07625858, 0.57457056, 0.7993518 , 0.66914789],
       [0.05224475, 0.5189414 , 0.07628665, 0.86668971, 0.94733648],
       [0.08941566, 0.8404441 , 0.5366776 , 0.71666552, 0.40674888],
       [0.35370325, 0.35211874, 0.27304017, 0.16508863, 0.85634705]])

In [408]:
q = np.random.randint(1,25, (3,5))
q

array([[ 1,  1, 11,  2,  5],
       [14, 20,  2,  8,  9],
       [10, 10,  3,  3,  1]])

In [412]:
np.dot(q,p)

array([[ 4.0531298 ,  9.60693475,  4.5903996 , 13.26341993, 16.72050447],
       [30.0817739 , 17.78741987, 28.72844516, 34.34343673, 33.73465733],
       [16.08958445,  9.00124961, 15.23883737, 19.62574339, 16.9643049 ]])

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [414]:
np.trace(p)

2.4827528173364084

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [420]:
q

array([[ 1,  1, 11,  2,  5],
       [14, 20,  2,  8,  9],
       [10, 10,  3,  3,  1]])

In [424]:
np.roll(q,1,axis = 0) #first and last rows are swapped

array([[10, 10,  3,  3,  1],
       [ 1,  1, 11,  2,  5],
       [14, 20,  2,  8,  9]])

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [452]:
q = np.arange(7)
q

array([0, 1, 2, 3, 4, 5, 6])

In [458]:
q.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [464]:
np.linalg.det(m)

58361283.00000004

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [468]:
r = np.arange(4).reshape(2,2)
r

array([[0, 1],
       [2, 3]])

In [470]:
np.linalg.eig(r)

EigResult(eigenvalues=array([-0.56155281,  3.56155281]), eigenvectors=array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]]))

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [472]:
s = np.array([[1, 2], [3, 5]])
t = np.array([1, 2])
u = np.linalg.solve(s, t)
u

array([-1.,  1.])

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [484]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [492]:
v = np.random.normal(0.5,0.3,x.shape) #generate noise according to normal distribution
x + v #add noise to the original array

array([ 0.89809258,  2.83992003,  3.10145359,  4.39441166,  5.51261305,
        6.54498788,  7.89257777,  7.93715888,  9.80217082, 10.3154024 ])

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [498]:
w = np.arange(16).reshape(4,4) #create 4X4 matrix 
np.diag(w) #extract values at diagonal

array([ 0,  5, 10, 15])

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---